server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_aplication
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_scheme: public
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  aplication:
    name: ecommerce-dio-project