server:
  port: 8080
  servlet:
    context-path: /v1
spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_scheme: public
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  aplication:
    name: ecommerce-dio-project